name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Criar cypress.env.json
        run: |
          echo '{
            "user_name": "${{ secrets.CYPRESS_USER_NAME }}",
            "user_password": "${{ secrets.CYPRESS_USER_PASSWORD }}"
          }' > cypress.env.json
